### ISSUE TITLE
numpy not listed as a dependency in setup.py

### ISSUE THREAD

**Issue by rogerhurwitz** [flatironinstitute/kachery#1]
PIP installed kachery into a clean venv environment, attempted to run sample code, and encountered the error below.  Resolved the problem by installing numpy.  Recommend adding numpy to install_requires section of setup.py.

`(kachery) ~ $ kachery-store test.py
Traceback (most recent call last):
  File "/home/rogerhurwitz/venv/kachery/bin/kachery-store", line 7, in <module>
    import kachery as ka
  File "/home/rogerhurwitz/venv/kachery/lib/python3.8/site-packages/kachery/__init__.py", line 1, in <module>
    from .core import set_config, get_config
  File "/home/rogerhurwitz/venv/kachery/lib/python3.8/site-packages/kachery/core.py", line 2, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'`

**Comment by magland** [comment]
Thanks @rogerhurwitz  for the report. The reason I left it out is that numpy is a unique package in that some users have a special installation of numpy on their system outside of a virtual environment. Therefore, I am going to add a line in the README explaining that it should be installed ahead of time.
